### ISSUE TITLE
'proton.exceptions' module seems to be missing

### ISSUE THREAD

**Issue by rollwagen** [ProtonVPN/protonvpn-nm-lib#5]
The required/used module **proton.exceptions** does not seem to be part of codebase nor dependencies (run 
 `pipenv install`/`pipenv install --dev` successfully), so running simple examples (as e.g. the 'How to use' from README) fails.
I'd assume that proton.exceptions (respectively exceptions such as e.g. the required ConnectionTimeOutError) will still be in included in codebase, or, where can it be found?
Many thanks in advance for the advise!

```
Traceback (most recent call last):
  File "./test.py", line 6, in <module>
    protonvpn.login("protonvpn@protonmail.com", "ProtonPassword")
  File "/home/ubuntu/github/proton/protonvpn-nm-lib/protonvpn_nm_lib/api.py", line 30, in login
    self._env.api_session.authenticate(username, password)
  File "/home/ubuntu/github/proton/protonvpn-nm-lib/protonvpn_nm_lib/core/session/session.py", line 21, in __call__
    from proton.exceptions import (ConnectionTimeOutError,
ModuleNotFoundError: No module named 'proton.exceptions'
```

**Comment by rollwagen** [comment]
Update:  **proton.exceptions** is defined/provided by package 'proton-client' (see Pipfile and requirements.txt) file proton/exceptions.py; however, latest available version 0.4.1. of proton-client on pypi https://pypi.org/project/proton-client/ does not (yet?) have the exceptions.py file.
python-client release 0.5.1 on Github has this (https://github.com/ProtonMail/proton-python-client/releases/tag/0.5.1) but package does not yet seem to be available on pypi.

```
proton-client-0.4.1 ls proton/
__init__.py      api.py           cert_pinning.py  constants.py     srp/
```

**Comment by calexandru2018** [comment]
Hey @rollwagen 

We currently don't support installations via pypi. Please either follow the install instructions at https://protonvpn.com/support/linux-vpn-setup/ or install them directly from Github.

**Comment by rollwagen** [comment]
@calexandru2018  - thanks for your reply.
FYI - was following the instructions as per REAME "Virtual Environment Dependencies  /  Install inside virtual environment" to get a (development) environment up. That's when I run into the proton-client (version) dependency issue described above.

**Comment by calexandru2018** [comment]
I understand, but given that we don't have all of our packages on pypi, there's no feasible way of doing such installs. With Virtua environment is oudl recommend creating a folder, in the git clone all the projects and install the packages inside the venv.
